<?php

/**
 * This is the model base class for the table "goal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Goal".
 *
 * Columns in table "goal" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $created_timestamp
 * @property string $title
 * @property string $desc
 * @property integer $user
 *
 */
abstract class BaseGoal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'goal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Goal|Goals', $n);
	}

	public static function representingColumn() {
		return 'created_timestamp';
	}

	public function rules() {
		return array(
			array('id, created_timestamp, title, desc, user', 'required'),
			array('id, user', 'numerical', 'integerOnly'=>true),
			array('title, desc', 'length', 'max'=>2048),
			array('id, created_timestamp, title, desc, user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'created_timestamp' => Yii::t('app', 'Created Timestamp'),
			'title' => Yii::t('app', 'Title'),
			'desc' => Yii::t('app', 'Desc'),
			'user' => Yii::t('app', 'User'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('created_timestamp', $this->created_timestamp, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('desc', $this->desc, true);
		$criteria->compare('user', $this->user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}